#!/bin/sh
# entrypoint.sh — Collibra Edge Site server container entrypoint
#
# Required environment variables:
#   COLLIBRA_EDGE_HOSTNAME    FQDN of this edge node
#   COLLIBRA_DGC_URL          Base URL of the Collibra DGC instance
#   COLLIBRA_EDGE_SITE_ID     Stable site identifier
#   COLLIBRA_EDGE_REG_KEY     Registration key from Collibra DGC admin console
#
# Optional:
#   COLLIBRA_EDGE_SITE_NAME   Display name (default: value of SITE_ID)
#   EDGE_SITE_HTTP_PORT       HTTP listen port (default: 8080)
#   EDGE_SITE_CAPABILITIES    Comma-separated list: connect,catalog,lineage,
#                             profiling,site,workflow  (default: site)
#   JAVA_OPTS                 JVM flags (default set in Dockerfile)

set -e

SITE_HOME="${EDGE_SITE_HOME:-/opt/edge/site}"
JAR="${SITE_HOME}/edge-site-server.jar"
LOG_DIR="${SITE_HOME}/logs"
CONFIG_DIR="${SITE_HOME}/config"
SITE_ID="${COLLIBRA_EDGE_SITE_ID:-}"
SITE_NAME="${COLLIBRA_EDGE_SITE_NAME:-${SITE_ID}}"
HTTP_PORT="${EDGE_SITE_HTTP_PORT:-8080}"
CAPABILITIES="${EDGE_SITE_CAPABILITIES:-site}"

# ── Validate required variables ───────────────────────────────────────────────
_require() {
  if [ -z "$(eval echo \$$1)" ]; then
    echo "[edge-site] ERROR: $1 is not set" >&2
    exit 1
  fi
}

_require COLLIBRA_EDGE_HOSTNAME
_require COLLIBRA_DGC_URL
_require COLLIBRA_EDGE_SITE_ID

# Registration key is optional at startup — if blank, DGC registration is skipped
if [ -z "${COLLIBRA_EDGE_REG_KEY:-}" ]; then
  echo "[edge-site] WARNING: COLLIBRA_EDGE_REG_KEY is not set — DGC registration will be skipped"
  echo "[edge-site] WARNING: Set COLLIBRA_EDGE_REG_KEY from: Settings > Edge Sites > ${COLLIBRA_EDGE_SITE_ID} > Generate Key"
fi

# ── Write site.properties ─────────────────────────────────────────────────────
cat > "${CONFIG_DIR}/site.properties" <<EOF
# Collibra Edge Site runtime properties
# Generated by entrypoint.sh — do not edit manually

collibra.edge.site.id=${SITE_ID}
collibra.edge.site.name=${SITE_NAME}
collibra.edge.hostname=${COLLIBRA_EDGE_HOSTNAME}
collibra.dgc.url=${COLLIBRA_DGC_URL}
collibra.edge.http.port=${HTTP_PORT}
collibra.edge.capabilities=${CAPABILITIES}
collibra.edge.site.content.root=${SITE_HOME}/www

# Java runtime
java.home=/usr/lib/jvm/jre-11-openjdk

# Collibra catalog governance reference
# collibraId=
EOF

echo "[edge-site] site.properties written"
echo "[edge-site] site-id=${SITE_ID}  hostname=${COLLIBRA_EDGE_HOSTNAME}  dgc=${COLLIBRA_DGC_URL}"
echo "[edge-site] capabilities=${CAPABILITIES}"
echo "[edge-site] starting JVM on port ${HTTP_PORT}..."

# ── Start the edge site server ────────────────────────────────────────────────
exec "${JAVA_HOME}/bin/java" \
  ${JAVA_OPTS} \
  -Dcollibra.edge.site.config="${CONFIG_DIR}/site.properties" \
  -Dcollibra.edge.registration.key="${COLLIBRA_EDGE_REG_KEY}" \
  -Dcollibra.edge.site.id="${SITE_ID}" \
  -Dcollibra.edge.hostname="${COLLIBRA_EDGE_HOSTNAME}" \
  -Dcollibra.dgc.url="${COLLIBRA_DGC_URL}" \
  -Dcollibra.edge.http.port="${HTTP_PORT}" \
  -Dcollibra.edge.capabilities="${CAPABILITIES}" \
  -jar "${JAR}" \
  "$@"
